"""Vision modules for person, hand, item, and container signals."""

from shoplift.vision.object_container import (
    CANONICAL_ITEM_CONTAINER_CLASSES,
    CONTAINER_CATEGORIES,
    EXTENSION_REGION_CATEGORIES,
    ITEM_AND_CONTAINER_ALIASES,
    ITEM_AND_CONTAINER_CLASSES,
    ITEM_CATEGORIES,
    NORMAL_CONTAINER_CATEGORIES,
    ItemContainerDetectionAdapter,
    ItemContainerResult,
    adapt_item_container_detections,
    canonical_item_container_category,
    detection_role,
)
from shoplift.vision.body_pose import (
    BodyPoseBuilder,
    COCO_PERSON_KEYPOINT_NAMES,
    COCO_PERSON_SKELETON,
)
from shoplift.vision.person_gate import (
    PersonGate,
    PersonGateMetrics,
    PersonGateResult,
    evaluate_person_gate,
)
from shoplift.vision.person_attribute import (
    BODY_ORIENTATION_LABELS,
    HAND_STATE_LABELS,
    HAND_VISIBILITY_LABELS,
    OCCLUSION_LEVEL_LABELS,
    PersonAttributeConfig,
    PersonAttributeFrameResult,
    PersonAttributePostProcessor,
    ProxyItemRegionBuilder,
    RuleBasedPersonAttributeEstimator,
    build_proxy_item_regions,
)
from shoplift.vision.pose_hand import (
    COCO_KEYPOINT_INDICES,
    HandRegionExtractor,
    PersonPose,
    build_person_poses,
    extract_hand_regions,
)

__all__ = [
    "CANONICAL_ITEM_CONTAINER_CLASSES",
    "BodyPoseBuilder",
    "BODY_ORIENTATION_LABELS",
    "COCO_KEYPOINT_INDICES",
    "COCO_PERSON_KEYPOINT_NAMES",
    "COCO_PERSON_SKELETON",
    "CONTAINER_CATEGORIES",
    "EXTENSION_REGION_CATEGORIES",
    "HandRegionExtractor",
    "HAND_STATE_LABELS",
    "HAND_VISIBILITY_LABELS",
    "ITEM_AND_CONTAINER_ALIASES",
    "ITEM_AND_CONTAINER_CLASSES",
    "ITEM_CATEGORIES",
    "ItemContainerDetectionAdapter",
    "ItemContainerResult",
    "NORMAL_CONTAINER_CATEGORIES",
    "OCCLUSION_LEVEL_LABELS",
    "PersonAttributeConfig",
    "PersonAttributeFrameResult",
    "PersonAttributePostProcessor",
    "PersonGate",
    "PersonGateMetrics",
    "PersonGateResult",
    "PersonPose",
    "ProxyItemRegionBuilder",
    "RuleBasedPersonAttributeEstimator",
    "adapt_item_container_detections",
    "build_proxy_item_regions",
    "build_person_poses",
    "canonical_item_container_category",
    "detection_role",
    "evaluate_person_gate",
    "extract_hand_regions",
]
